platform :ios, '16.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'StreamBrowser' do
  # Community-maintained prebuilt FFmpegKit iOS frameworks. The min bundle
  # includes the FFmpeg codecs needed to decode MPEG-2 transport streams.
  pod 'ffmpeg-mobile-min',
      :podspec => 'https://raw.githubusercontent.com/maitrungduc1410/ffmpegkit-ios/master/min/ffmpeg-mobile-min.podspec'
end